FROM node:lts-alpine

# install simple http server for serving static content
RUN npm install -g http-server

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install vue@next --save
RUN npm install vue-router@next --save

EXPOSE 8080
CMD [ "http-server", "dist" ]
